//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class YSG_Booking_Catering_info
{
    public Nullable<decimal> Booking_no { get; set; }
    public Nullable<decimal> Caterer_No { get; set; }
    public Nullable<System.DateTime> event_Date { get; set; }
    public string FoodType { get; set; }
    public Nullable<decimal> Persons { get; set; }
    public Nullable<decimal> Rate_per_person { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public decimal Booking_Catering_info_No { get; set; }

    public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
    public virtual YSG_Caterer_Master YSG_Caterer_Master { get; set; }
}

public partial class YSG_Booking_Contact_Persons
{
    public Nullable<decimal> Booking_No { get; set; }
    public string Contact_name { get; set; }
    public string Contact_No { get; set; }
    public string Contact_Email_id { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }
    public decimal Booking_Contact_Person_No { get; set; }

    public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
}

public partial class YSG_Booking_Facilities
{
    public Nullable<decimal> Booking_No { get; set; }
    public Nullable<decimal> Item_no { get; set; }
    public Nullable<decimal> Required_Qty { get; set; }
    public Nullable<decimal> Calculated_Amount { get; set; }
    public string Remarks { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }
    public decimal Booking_Facility_No { get; set; }
    public string IsActive { get; set; }

    public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
    public virtual YSG_Inventory_Master YSG_Inventory_Master { get; set; }
}

public partial class YSG_Booking_Hall_Info
{
    public int ID { get; set; }
    public Nullable<decimal> Booking_No { get; set; }
    public Nullable<decimal> Hall_no { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }

    public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
    public virtual YSG_Hall_Master YSG_Hall_Master { get; set; }
}

public partial class YSG_Booking_Info
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public YSG_Booking_Info()
    {
        this.YSG_Booking_Catering_info = new HashSet<YSG_Booking_Catering_info>();
        this.YSG_Booking_Contact_Persons = new HashSet<YSG_Booking_Contact_Persons>();
        this.YSG_Booking_Facilities = new HashSet<YSG_Booking_Facilities>();
        this.YSG_Booking_Hall_Info = new HashSet<YSG_Booking_Hall_Info>();
        this.YSG_Booking_Payment = new HashSet<YSG_Booking_Payment>();
        this.YSG_Feedback = new HashSet<YSG_Feedback>();
        this.YSG_My_To_Do_List = new HashSet<YSG_My_To_Do_List>();
    }

    public decimal Booking_No { get; set; }
    public Nullable<decimal> Booking_ID { get; set; }
    public Nullable<System.DateTime> Booking_Date { get; set; }
    public Nullable<System.DateTime> Booking_FromTime { get; set; }
    public Nullable<System.DateTime> Booking_ToTime { get; set; }
    public Nullable<decimal> Event_no { get; set; }
    public string Event_Class { get; set; }
    public Nullable<decimal> Customer_no { get; set; }
    public string Booking_Status { get; set; }
    public Nullable<decimal> No_Of_Invitees { get; set; }
    public Nullable<decimal> Booking_calculated_Amt { get; set; }
    public Nullable<decimal> Discount { get; set; }
    public string Discount_Reason { get; set; }
    public Nullable<decimal> Booking_final_Amt { get; set; }
    public string RemarkOrComments { get; set; }
    public Nullable<decimal> Paid_Amt { get; set; }
    public Nullable<decimal> Balance_Amt { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }
    public string IsActive { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Booking_Catering_info> YSG_Booking_Catering_info { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Booking_Contact_Persons> YSG_Booking_Contact_Persons { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Booking_Facilities> YSG_Booking_Facilities { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Booking_Hall_Info> YSG_Booking_Hall_Info { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Booking_Payment> YSG_Booking_Payment { get; set; }
    public virtual YSG_Event_Master YSG_Event_Master { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Feedback> YSG_Feedback { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_My_To_Do_List> YSG_My_To_Do_List { get; set; }
    public virtual YSG_Customer_Info YSG_Customer_Info { get; set; }
}

public partial class YSG_Booking_Payment
{
    public Nullable<decimal> Booking_No { get; set; }
    public decimal Payment_No { get; set; }
    public string Payment_Account_Head { get; set; }
    public Nullable<System.DateTime> Payment_Date { get; set; }
    public string Cash_Cheque_Card { get; set; }
    public string Bank_Name { get; set; }
    public string Cheque_Card_No { get; set; }
    public Nullable<System.DateTime> Cheque_Date { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public string Amount_In_Words { get; set; }
    public string Payment_Status { get; set; }
    public string Remarks { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }

    public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
}

public partial class YSG_Caterer_Master
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public YSG_Caterer_Master()
    {
        this.YSG_Booking_Catering_info = new HashSet<YSG_Booking_Catering_info>();
    }

    public decimal Caterer_No { get; set; }
    public string Caterer_Name { get; set; }
    public string Contact_NUMERIC { get; set; }
    public string Remarks { get; set; }
    public Nullable<decimal> Created_by { get; set; }
    public Nullable<System.DateTime> created_Datetime { get; set; }
    public Nullable<decimal> updated_by { get; set; }
    public Nullable<System.DateTime> updated_datetime { get; set; }
    public string is_Active { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Booking_Catering_info> YSG_Booking_Catering_info { get; set; }
}

public partial class YSG_Customer_Info
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public YSG_Customer_Info()
    {
        this.YSG_Booking_Info = new HashSet<YSG_Booking_Info>();
    }

    public decimal Customer_no { get; set; }
    public string Customer_name { get; set; }
    public string Customer_Address { get; set; }
    public string Landline_No { get; set; }
    public string Fax_No { get; set; }
    public string Mobile_No { get; set; }
    public string Email_id { get; set; }
    public string Customer_Status { get; set; }
    public string Referred_By { get; set; }
    public string Customer_Type { get; set; }
    public string Comments { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Booking_Info> YSG_Booking_Info { get; set; }
}

public partial class YSG_Department_Master
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public YSG_Department_Master()
    {
        this.YSG_Employee_Master = new HashSet<YSG_Employee_Master>();
        this.YSG_Inventory_Master = new HashSet<YSG_Inventory_Master>();
    }

    public decimal Dept_no { get; set; }
    public string Dept_name { get; set; }
    public Nullable<decimal> IsActive { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Employee_Master> YSG_Employee_Master { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Inventory_Master> YSG_Inventory_Master { get; set; }
}

public partial class YSG_Employee_Master
{
    public decimal Emp_no { get; set; }
    public string Emp_name { get; set; }
    public Nullable<decimal> Mobile_No { get; set; }
    public string Email_id { get; set; }
    public Nullable<decimal> Dept_no { get; set; }
    public Nullable<decimal> IsDept_Head { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }

    public virtual YSG_Department_Master YSG_Department_Master { get; set; }
}

public partial class YSG_Event_Master
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public YSG_Event_Master()
    {
        this.YSG_Booking_Info = new HashSet<YSG_Booking_Info>();
    }

    public decimal Event_no { get; set; }
    public string Event_name { get; set; }
    public string Description { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Booking_Info> YSG_Booking_Info { get; set; }
}

public partial class YSG_Feedback
{
    public decimal Feedback_No { get; set; }
    public Nullable<decimal> Booking_No { get; set; }
    public string QuestionOrCriteria { get; set; }
    public Nullable<decimal> Ratings { get; set; }
    public string Remarks { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }

    public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
}

public partial class YSG_Hall_Master
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public YSG_Hall_Master()
    {
        this.YSG_Booking_Hall_Info = new HashSet<YSG_Booking_Hall_Info>();
    }

    public decimal Hall_no { get; set; }
    public string Hall_name { get; set; }
    public Nullable<decimal> Capacity_seating { get; set; }
    public Nullable<decimal> Capacity_chairs { get; set; }
    public Nullable<decimal> Rent_per_hour { get; set; }
    public string Description { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Booking_Hall_Info> YSG_Booking_Hall_Info { get; set; }
    public virtual YSG_Hall_Master YSG_Hall_Master1 { get; set; }
    public virtual YSG_Hall_Master YSG_Hall_Master2 { get; set; }
}

public partial class YSG_Inventory_Master
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public YSG_Inventory_Master()
    {
        this.YSG_Booking_Facilities = new HashSet<YSG_Booking_Facilities>();
    }

    public decimal Item_no { get; set; }
    public string Item_name { get; set; }
    public Nullable<decimal> Related_Dept_No { get; set; }
    public Nullable<decimal> Available_Qty { get; set; }
    public Nullable<decimal> Rent_per_Qty { get; set; }
    public string Description { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }
    public string IsActive { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_Booking_Facilities> YSG_Booking_Facilities { get; set; }
    public virtual YSG_Department_Master YSG_Department_Master { get; set; }
}

public partial class YSG_My_To_Do_List
{
    public Nullable<decimal> User_No { get; set; }
    public Nullable<decimal> Booking_No { get; set; }
    public Nullable<System.DateTime> Task_Date { get; set; }
    public Nullable<System.DateTime> Reminder_DateTime { get; set; }
    public string Task_Description { get; set; }
    public Nullable<decimal> Dept_No { get; set; }
    public string Task_Status { get; set; }
    public string Remarks { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }
    public decimal Task_ID { get; set; }

    public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
}

public partial class YSG_Role_Master
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public YSG_Role_Master()
    {
        this.YSG_User_Master = new HashSet<YSG_User_Master>();
    }

    public decimal Role_no { get; set; }
    public string Role_name { get; set; }
    public string Remarks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<YSG_User_Master> YSG_User_Master { get; set; }
}

public partial class YSG_Tithi_Info
{
    public System.DateTime Tithi_Date { get; set; }
    public string Tithi { get; set; }
    public string Description { get; set; }
}

public partial class YSG_User_Master
{
    public decimal user_no { get; set; }
    public string user_login_id { get; set; }
    public string User_password { get; set; }
    public string reset_password { get; set; }
    public string user_name { get; set; }
    public Nullable<decimal> Mobile_No { get; set; }
    public string Email_id { get; set; }
    public Nullable<System.DateTime> Last_login_datetime { get; set; }
    public Nullable<decimal> Role_no { get; set; }
    public string IsActive { get; set; }
    public Nullable<decimal> created_By { get; set; }
    public Nullable<System.DateTime> created_datetime { get; set; }
    public Nullable<decimal> Updated_By { get; set; }
    public Nullable<System.DateTime> Updated_Datetime { get; set; }

    public virtual YSG_Role_Master YSG_Role_Master { get; set; }
}

public partial class GetTithiInfo_Result
{
    public System.DateTime Tithi_Date { get; set; }
    public string TithiName { get; set; }
    public string Description { get; set; }
}
