//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSGOps.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YSG_Booking_Payment
    {
        public Nullable<decimal> Booking_No { get; set; }
        public decimal Payment_No { get; set; }
        public string Payment_Account_Head { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string Cash_Cheque_Card { get; set; }
        public string Bank_Name { get; set; }
        public string Cheque_Card_No { get; set; }
        public Nullable<System.DateTime> Cheque_Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Amount_In_Words { get; set; }
        public string Payment_Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> created_By { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<decimal> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Datetime { get; set; }
    
        public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
    }
}
