//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSGOps.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YSG_Employee_Master
    {
        public decimal Emp_no { get; set; }
        public string Emp_name { get; set; }
        public Nullable<decimal> Mobile_No { get; set; }
        public string Email_id { get; set; }
        public Nullable<decimal> Dept_no { get; set; }
        public Nullable<decimal> IsDept_Head { get; set; }
        public Nullable<decimal> created_By { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<decimal> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Datetime { get; set; }
    
        public virtual YSG_Department_Master YSG_Department_Master { get; set; }
    }
}
