//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSGOps.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YSG_Caterer_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YSG_Caterer_Master()
        {
            this.YSG_Booking_Catering_info = new HashSet<YSG_Booking_Catering_info>();
        }
    
        public decimal Caterer_No { get; set; }
        public string Caterer_Name { get; set; }
        public string Contact_NUMERIC { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Created_by { get; set; }
        public Nullable<System.DateTime> created_Datetime { get; set; }
        public Nullable<decimal> updated_by { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public string is_Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YSG_Booking_Catering_info> YSG_Booking_Catering_info { get; set; }
    }
}
