//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSGOps.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YSG_Customer_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YSG_Customer_Info()
        {
            this.YSG_Booking_Info = new HashSet<YSG_Booking_Info>();
        }
    
        public decimal Customer_no { get; set; }
        public string Customer_name { get; set; }
        public string Customer_Address { get; set; }
        public string Landline_No { get; set; }
        public string Fax_No { get; set; }
        public string Mobile_No { get; set; }
        public string Email_id { get; set; }
        public string Customer_Status { get; set; }
        public string Referred_By { get; set; }
        public string Customer_Type { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> created_By { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<decimal> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Datetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YSG_Booking_Info> YSG_Booking_Info { get; set; }
    }
}
