//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSGOps.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YSG_My_To_Do_List
    {
        public Nullable<decimal> User_No { get; set; }
        public Nullable<decimal> Booking_No { get; set; }
        public Nullable<System.DateTime> Task_Date { get; set; }
        public Nullable<System.DateTime> Reminder_DateTime { get; set; }
        public string Task_Description { get; set; }
        public Nullable<decimal> Dept_No { get; set; }
        public string Task_Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> created_By { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<decimal> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Datetime { get; set; }
        public decimal Task_ID { get; set; }
    
        public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
    }
}
