//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSGOps.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YSG_Booking_Catering_info
    {
        public Nullable<decimal> Booking_no { get; set; }
        public Nullable<decimal> Caterer_No { get; set; }
        public Nullable<System.DateTime> event_Date { get; set; }
        public string FoodType { get; set; }
        public Nullable<decimal> Persons { get; set; }
        public Nullable<decimal> Rate_per_person { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal Booking_Catering_info_No { get; set; }
    
        public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
        public virtual YSG_Caterer_Master YSG_Caterer_Master { get; set; }
    }
}
