//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSGOps.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YSG_Booking_Facilities
    {
        public Nullable<decimal> Booking_No { get; set; }
        public Nullable<decimal> Item_no { get; set; }
        public Nullable<decimal> Required_Qty { get; set; }
        public Nullable<decimal> Calculated_Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> created_By { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<decimal> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Datetime { get; set; }
        public decimal Booking_Facility_No { get; set; }
        public string IsActive { get; set; }
    
        public virtual YSG_Booking_Info YSG_Booking_Info { get; set; }
        public virtual YSG_Inventory_Master YSG_Inventory_Master { get; set; }
    }
}
