//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSGOps.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YSG_Hall_Master
    {
        public decimal Hall_no { get; set; }
        public string Hall_name { get; set; }
        public Nullable<decimal> Capicity_seating { get; set; }
        public Nullable<decimal> Capicity_chairs { get; set; }
        public Nullable<decimal> Rent_per_hour { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> created_By { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<decimal> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Datetime { get; set; }
    }
}
