//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSGOps.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YogiSabhaGruhEntities : DbContext
    {
        public YogiSabhaGruhEntities()
            : base("name=YogiSabhaGruhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<YSG_Booking_Catering_info> YSG_Booking_Catering_info { get; set; }
        public virtual DbSet<YSG_Booking_Contact_Persons> YSG_Booking_Contact_Persons { get; set; }
        public virtual DbSet<YSG_Booking_Facilities> YSG_Booking_Facilities { get; set; }
        public virtual DbSet<YSG_Booking_Info> YSG_Booking_Info { get; set; }
        public virtual DbSet<YSG_Booking_Payment> YSG_Booking_Payment { get; set; }
        public virtual DbSet<YSG_Caterer_Master> YSG_Caterer_Master { get; set; }
        public virtual DbSet<YSG_Customer_Info> YSG_Customer_Info { get; set; }
        public virtual DbSet<YSG_Department_Master> YSG_Department_Master { get; set; }
        public virtual DbSet<YSG_Employee_Master> YSG_Employee_Master { get; set; }
        public virtual DbSet<YSG_Event_Master> YSG_Event_Master { get; set; }
        public virtual DbSet<YSG_Feedback> YSG_Feedback { get; set; }
        public virtual DbSet<YSG_Hall_Master> YSG_Hall_Master { get; set; }
        public virtual DbSet<YSG_Inventory_Master> YSG_Inventory_Master { get; set; }
        public virtual DbSet<YSG_My_To_Do_List> YSG_My_To_Do_List { get; set; }
        public virtual DbSet<YSG_Role_Master> YSG_Role_Master { get; set; }
        public virtual DbSet<YSG_User_Master> YSG_User_Master { get; set; }
        public virtual DbSet<YSG_Tithi_Info> YSG_Tithi_Info { get; set; }
        public virtual DbSet<YSG_Booking_Hall_Info> YSG_Booking_Hall_Info { get; set; }
    
        public virtual int ADD_YSG_Customer_Info(string customer_name, string customer_Address, string landline_No, string fax_No, string mobile_No, string email_id, string customer_Status, string referred_By, string customer_Type, string comments, Nullable<decimal> created_By)
        {
            var customer_nameParameter = customer_name != null ?
                new ObjectParameter("Customer_name", customer_name) :
                new ObjectParameter("Customer_name", typeof(string));
    
            var customer_AddressParameter = customer_Address != null ?
                new ObjectParameter("Customer_Address", customer_Address) :
                new ObjectParameter("Customer_Address", typeof(string));
    
            var landline_NoParameter = landline_No != null ?
                new ObjectParameter("Landline_No", landline_No) :
                new ObjectParameter("Landline_No", typeof(string));
    
            var fax_NoParameter = fax_No != null ?
                new ObjectParameter("Fax_No", fax_No) :
                new ObjectParameter("Fax_No", typeof(string));
    
            var mobile_NoParameter = mobile_No != null ?
                new ObjectParameter("Mobile_No", mobile_No) :
                new ObjectParameter("Mobile_No", typeof(string));
    
            var email_idParameter = email_id != null ?
                new ObjectParameter("Email_id", email_id) :
                new ObjectParameter("Email_id", typeof(string));
    
            var customer_StatusParameter = customer_Status != null ?
                new ObjectParameter("Customer_Status", customer_Status) :
                new ObjectParameter("Customer_Status", typeof(string));
    
            var referred_ByParameter = referred_By != null ?
                new ObjectParameter("Referred_By", referred_By) :
                new ObjectParameter("Referred_By", typeof(string));
    
            var customer_TypeParameter = customer_Type != null ?
                new ObjectParameter("Customer_Type", customer_Type) :
                new ObjectParameter("Customer_Type", typeof(string));
    
            var commentsParameter = comments != null ?
                new ObjectParameter("Comments", comments) :
                new ObjectParameter("Comments", typeof(string));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("created_By", created_By) :
                new ObjectParameter("created_By", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_YSG_Customer_Info", customer_nameParameter, customer_AddressParameter, landline_NoParameter, fax_NoParameter, mobile_NoParameter, email_idParameter, customer_StatusParameter, referred_ByParameter, customer_TypeParameter, commentsParameter, created_ByParameter);
        }
    
        public virtual int ADD_YSG_Event_Master(string event_name, string description, Nullable<decimal> created_By)
        {
            var event_nameParameter = event_name != null ?
                new ObjectParameter("Event_name", event_name) :
                new ObjectParameter("Event_name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("created_By", created_By) :
                new ObjectParameter("created_By", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_YSG_Event_Master", event_nameParameter, descriptionParameter, created_ByParameter);
        }
    
        public virtual int ADD_YSG_Hall_Master(string hall_name, Nullable<decimal> capacity_seating, Nullable<decimal> capacity_chairs, Nullable<decimal> rent_per_hour, string description, Nullable<decimal> created_By)
        {
            var hall_nameParameter = hall_name != null ?
                new ObjectParameter("Hall_name", hall_name) :
                new ObjectParameter("Hall_name", typeof(string));
    
            var capacity_seatingParameter = capacity_seating.HasValue ?
                new ObjectParameter("Capacity_seating", capacity_seating) :
                new ObjectParameter("Capacity_seating", typeof(decimal));
    
            var capacity_chairsParameter = capacity_chairs.HasValue ?
                new ObjectParameter("Capacity_chairs", capacity_chairs) :
                new ObjectParameter("Capacity_chairs", typeof(decimal));
    
            var rent_per_hourParameter = rent_per_hour.HasValue ?
                new ObjectParameter("Rent_per_hour", rent_per_hour) :
                new ObjectParameter("Rent_per_hour", typeof(decimal));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("created_By", created_By) :
                new ObjectParameter("created_By", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_YSG_Hall_Master", hall_nameParameter, capacity_seatingParameter, capacity_chairsParameter, rent_per_hourParameter, descriptionParameter, created_ByParameter);
        }
    
        public virtual int AUD_Booking_Contact_Persons(Nullable<decimal> booking_No, string contact_name, string contact_No, string contact_Email_id, Nullable<decimal> created_By, string aCTION, Nullable<decimal> booking_Contact_Person_No)
        {
            var booking_NoParameter = booking_No.HasValue ?
                new ObjectParameter("Booking_No", booking_No) :
                new ObjectParameter("Booking_No", typeof(decimal));
    
            var contact_nameParameter = contact_name != null ?
                new ObjectParameter("Contact_name", contact_name) :
                new ObjectParameter("Contact_name", typeof(string));
    
            var contact_NoParameter = contact_No != null ?
                new ObjectParameter("Contact_No", contact_No) :
                new ObjectParameter("Contact_No", typeof(string));
    
            var contact_Email_idParameter = contact_Email_id != null ?
                new ObjectParameter("Contact_Email_id", contact_Email_id) :
                new ObjectParameter("Contact_Email_id", typeof(string));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("created_By", created_By) :
                new ObjectParameter("created_By", typeof(decimal));
    
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var booking_Contact_Person_NoParameter = booking_Contact_Person_No.HasValue ?
                new ObjectParameter("Booking_Contact_Person_No", booking_Contact_Person_No) :
                new ObjectParameter("Booking_Contact_Person_No", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AUD_Booking_Contact_Persons", booking_NoParameter, contact_nameParameter, contact_NoParameter, contact_Email_idParameter, created_ByParameter, aCTIONParameter, booking_Contact_Person_NoParameter);
        }
    
        public virtual int AUD_YSG_Booking_Facilities(string aCTION, Nullable<decimal> booking_Facility_No, Nullable<decimal> booking_No, Nullable<decimal> item_no, Nullable<decimal> required_Qty, Nullable<decimal> calculated_Amount, string remarks, Nullable<decimal> created_By)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var booking_Facility_NoParameter = booking_Facility_No.HasValue ?
                new ObjectParameter("Booking_Facility_No", booking_Facility_No) :
                new ObjectParameter("Booking_Facility_No", typeof(decimal));
    
            var booking_NoParameter = booking_No.HasValue ?
                new ObjectParameter("Booking_No", booking_No) :
                new ObjectParameter("Booking_No", typeof(decimal));
    
            var item_noParameter = item_no.HasValue ?
                new ObjectParameter("Item_no", item_no) :
                new ObjectParameter("Item_no", typeof(decimal));
    
            var required_QtyParameter = required_Qty.HasValue ?
                new ObjectParameter("Required_Qty", required_Qty) :
                new ObjectParameter("Required_Qty", typeof(decimal));
    
            var calculated_AmountParameter = calculated_Amount.HasValue ?
                new ObjectParameter("Calculated_Amount", calculated_Amount) :
                new ObjectParameter("Calculated_Amount", typeof(decimal));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("created_By", created_By) :
                new ObjectParameter("created_By", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AUD_YSG_Booking_Facilities", aCTIONParameter, booking_Facility_NoParameter, booking_NoParameter, item_noParameter, required_QtyParameter, calculated_AmountParameter, remarksParameter, created_ByParameter);
        }
    
        public virtual int AUD_YSG_Booking_Info(string action, Nullable<decimal> booking_No, Nullable<decimal> booking_ID, Nullable<System.DateTime> booking_Date, Nullable<System.DateTime> booking_FromTime, Nullable<System.DateTime> booking_ToTime, Nullable<decimal> event_no, string event_Class, Nullable<decimal> customer_no, string booking_Status, Nullable<decimal> no_Of_Invitees, Nullable<decimal> booking_calculated_Amt, Nullable<decimal> discount, string discount_Reason, Nullable<decimal> booking_final_Amt, string remarkOrComments, Nullable<decimal> paid_Amt, Nullable<decimal> balance_Amt, Nullable<decimal> created_By)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var booking_NoParameter = booking_No.HasValue ?
                new ObjectParameter("Booking_No", booking_No) :
                new ObjectParameter("Booking_No", typeof(decimal));
    
            var booking_IDParameter = booking_ID.HasValue ?
                new ObjectParameter("Booking_ID", booking_ID) :
                new ObjectParameter("Booking_ID", typeof(decimal));
    
            var booking_DateParameter = booking_Date.HasValue ?
                new ObjectParameter("Booking_Date", booking_Date) :
                new ObjectParameter("Booking_Date", typeof(System.DateTime));
    
            var booking_FromTimeParameter = booking_FromTime.HasValue ?
                new ObjectParameter("Booking_FromTime", booking_FromTime) :
                new ObjectParameter("Booking_FromTime", typeof(System.DateTime));
    
            var booking_ToTimeParameter = booking_ToTime.HasValue ?
                new ObjectParameter("Booking_ToTime", booking_ToTime) :
                new ObjectParameter("Booking_ToTime", typeof(System.DateTime));
    
            var event_noParameter = event_no.HasValue ?
                new ObjectParameter("Event_no", event_no) :
                new ObjectParameter("Event_no", typeof(decimal));
    
            var event_ClassParameter = event_Class != null ?
                new ObjectParameter("Event_Class", event_Class) :
                new ObjectParameter("Event_Class", typeof(string));
    
            var customer_noParameter = customer_no.HasValue ?
                new ObjectParameter("Customer_no", customer_no) :
                new ObjectParameter("Customer_no", typeof(decimal));
    
            var booking_StatusParameter = booking_Status != null ?
                new ObjectParameter("Booking_Status", booking_Status) :
                new ObjectParameter("Booking_Status", typeof(string));
    
            var no_Of_InviteesParameter = no_Of_Invitees.HasValue ?
                new ObjectParameter("No_Of_Invitees", no_Of_Invitees) :
                new ObjectParameter("No_Of_Invitees", typeof(decimal));
    
            var booking_calculated_AmtParameter = booking_calculated_Amt.HasValue ?
                new ObjectParameter("Booking_calculated_Amt", booking_calculated_Amt) :
                new ObjectParameter("Booking_calculated_Amt", typeof(decimal));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("Discount", discount) :
                new ObjectParameter("Discount", typeof(decimal));
    
            var discount_ReasonParameter = discount_Reason != null ?
                new ObjectParameter("Discount_Reason", discount_Reason) :
                new ObjectParameter("Discount_Reason", typeof(string));
    
            var booking_final_AmtParameter = booking_final_Amt.HasValue ?
                new ObjectParameter("Booking_final_Amt", booking_final_Amt) :
                new ObjectParameter("Booking_final_Amt", typeof(decimal));
    
            var remarkOrCommentsParameter = remarkOrComments != null ?
                new ObjectParameter("RemarkOrComments", remarkOrComments) :
                new ObjectParameter("RemarkOrComments", typeof(string));
    
            var paid_AmtParameter = paid_Amt.HasValue ?
                new ObjectParameter("Paid_Amt", paid_Amt) :
                new ObjectParameter("Paid_Amt", typeof(decimal));
    
            var balance_AmtParameter = balance_Amt.HasValue ?
                new ObjectParameter("Balance_Amt", balance_Amt) :
                new ObjectParameter("Balance_Amt", typeof(decimal));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("created_By", created_By) :
                new ObjectParameter("created_By", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AUD_YSG_Booking_Info", actionParameter, booking_NoParameter, booking_IDParameter, booking_DateParameter, booking_FromTimeParameter, booking_ToTimeParameter, event_noParameter, event_ClassParameter, customer_noParameter, booking_StatusParameter, no_Of_InviteesParameter, booking_calculated_AmtParameter, discountParameter, discount_ReasonParameter, booking_final_AmtParameter, remarkOrCommentsParameter, paid_AmtParameter, balance_AmtParameter, created_ByParameter);
        }
    
        public virtual int AUD_YSG_Inventory_Master(string aCTION, Nullable<decimal> item_no, string item_name, Nullable<decimal> related_Dept_No, Nullable<decimal> available_Qty, Nullable<decimal> rent_per_Qty, string description, Nullable<decimal> created_By)
        {
            var aCTIONParameter = aCTION != null ?
                new ObjectParameter("ACTION", aCTION) :
                new ObjectParameter("ACTION", typeof(string));
    
            var item_noParameter = item_no.HasValue ?
                new ObjectParameter("Item_no", item_no) :
                new ObjectParameter("Item_no", typeof(decimal));
    
            var item_nameParameter = item_name != null ?
                new ObjectParameter("Item_name", item_name) :
                new ObjectParameter("Item_name", typeof(string));
    
            var related_Dept_NoParameter = related_Dept_No.HasValue ?
                new ObjectParameter("Related_Dept_No", related_Dept_No) :
                new ObjectParameter("Related_Dept_No", typeof(decimal));
    
            var available_QtyParameter = available_Qty.HasValue ?
                new ObjectParameter("Available_Qty", available_Qty) :
                new ObjectParameter("Available_Qty", typeof(decimal));
    
            var rent_per_QtyParameter = rent_per_Qty.HasValue ?
                new ObjectParameter("Rent_per_Qty", rent_per_Qty) :
                new ObjectParameter("Rent_per_Qty", typeof(decimal));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var created_ByParameter = created_By.HasValue ?
                new ObjectParameter("created_By", created_By) :
                new ObjectParameter("created_By", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AUD_YSG_Inventory_Master", aCTIONParameter, item_noParameter, item_nameParameter, related_Dept_NoParameter, available_QtyParameter, rent_per_QtyParameter, descriptionParameter, created_ByParameter);
        }
    
        public virtual ObjectResult<GetTithiInfo_Result> GetTithiInfo(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTithiInfo_Result>("GetTithiInfo", startDateParameter, endDateParameter);
        }
    }
}
