//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSGOpsWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YogiSabhaGruhEntities : DbContext
    {
        public YogiSabhaGruhEntities()
            : base("name=YogiSabhaGruhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<YSG_Booking_Info> YSG_Booking_Info { get; set; }
        public virtual DbSet<YSG_Booking_Payment> YSG_Booking_Payment { get; set; }
        public virtual DbSet<YSG_Caterer_Master> YSG_Caterer_Master { get; set; }
        public virtual DbSet<YSG_Customer_Info> YSG_Customer_Info { get; set; }
        public virtual DbSet<YSG_Department_Master> YSG_Department_Master { get; set; }
        public virtual DbSet<YSG_Employee_Master> YSG_Employee_Master { get; set; }
        public virtual DbSet<YSG_Event_Master> YSG_Event_Master { get; set; }
        public virtual DbSet<YSG_Feedback> YSG_Feedback { get; set; }
        public virtual DbSet<YSG_Hall_Master> YSG_Hall_Master { get; set; }
        public virtual DbSet<YSG_Inventory_Master> YSG_Inventory_Master { get; set; }
        public virtual DbSet<YSG_Role_Master> YSG_Role_Master { get; set; }
        public virtual DbSet<YSG_User_Master> YSG_User_Master { get; set; }
    }
}
